/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const IndexLazyRouteImport = createFileRoute('/')()
const RoomIndexLazyRouteImport = createFileRoute('/room/')()
const ProfileIndexLazyRouteImport = createFileRoute('/profile/')()
const ProductIndexLazyRouteImport = createFileRoute('/product/')()
const MusicIndexLazyRouteImport = createFileRoute('/music/')()
const HiddenStoryIndexLazyRouteImport = createFileRoute('/hiddenStory/')()
const GameIndexLazyRouteImport = createFileRoute('/game/')()
const ContactIndexLazyRouteImport = createFileRoute('/contact/')()

const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const RoomIndexLazyRoute = RoomIndexLazyRouteImport.update({
  id: '/room/',
  path: '/room/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/room/index.lazy').then((d) => d.Route))
const ProfileIndexLazyRoute = ProfileIndexLazyRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/profile/index.lazy').then((d) => d.Route))
const ProductIndexLazyRoute = ProductIndexLazyRouteImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/product/index.lazy').then((d) => d.Route))
const MusicIndexLazyRoute = MusicIndexLazyRouteImport.update({
  id: '/music/',
  path: '/music/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/music/index.lazy').then((d) => d.Route))
const HiddenStoryIndexLazyRoute = HiddenStoryIndexLazyRouteImport.update({
  id: '/hiddenStory/',
  path: '/hiddenStory/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/hiddenStory/index.lazy').then((d) => d.Route),
)
const GameIndexLazyRoute = GameIndexLazyRouteImport.update({
  id: '/game/',
  path: '/game/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/game/index.lazy').then((d) => d.Route))
const ContactIndexLazyRoute = ContactIndexLazyRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/contact/index.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/contact': typeof ContactIndexLazyRoute
  '/game': typeof GameIndexLazyRoute
  '/hiddenStory': typeof HiddenStoryIndexLazyRoute
  '/music': typeof MusicIndexLazyRoute
  '/product': typeof ProductIndexLazyRoute
  '/profile': typeof ProfileIndexLazyRoute
  '/room': typeof RoomIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/contact': typeof ContactIndexLazyRoute
  '/game': typeof GameIndexLazyRoute
  '/hiddenStory': typeof HiddenStoryIndexLazyRoute
  '/music': typeof MusicIndexLazyRoute
  '/product': typeof ProductIndexLazyRoute
  '/profile': typeof ProfileIndexLazyRoute
  '/room': typeof RoomIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/contact/': typeof ContactIndexLazyRoute
  '/game/': typeof GameIndexLazyRoute
  '/hiddenStory/': typeof HiddenStoryIndexLazyRoute
  '/music/': typeof MusicIndexLazyRoute
  '/product/': typeof ProductIndexLazyRoute
  '/profile/': typeof ProfileIndexLazyRoute
  '/room/': typeof RoomIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/game'
    | '/hiddenStory'
    | '/music'
    | '/product'
    | '/profile'
    | '/room'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/game'
    | '/hiddenStory'
    | '/music'
    | '/product'
    | '/profile'
    | '/room'
  id:
    | '__root__'
    | '/'
    | '/contact/'
    | '/game/'
    | '/hiddenStory/'
    | '/music/'
    | '/product/'
    | '/profile/'
    | '/room/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ContactIndexLazyRoute: typeof ContactIndexLazyRoute
  GameIndexLazyRoute: typeof GameIndexLazyRoute
  HiddenStoryIndexLazyRoute: typeof HiddenStoryIndexLazyRoute
  MusicIndexLazyRoute: typeof MusicIndexLazyRoute
  ProductIndexLazyRoute: typeof ProductIndexLazyRoute
  ProfileIndexLazyRoute: typeof ProfileIndexLazyRoute
  RoomIndexLazyRoute: typeof RoomIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/': {
      id: '/room/'
      path: '/room'
      fullPath: '/room'
      preLoaderRoute: typeof RoomIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/': {
      id: '/product/'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music/': {
      id: '/music/'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hiddenStory/': {
      id: '/hiddenStory/'
      path: '/hiddenStory'
      fullPath: '/hiddenStory'
      preLoaderRoute: typeof HiddenStoryIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/': {
      id: '/game/'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ContactIndexLazyRoute: ContactIndexLazyRoute,
  GameIndexLazyRoute: GameIndexLazyRoute,
  HiddenStoryIndexLazyRoute: HiddenStoryIndexLazyRoute,
  MusicIndexLazyRoute: MusicIndexLazyRoute,
  ProductIndexLazyRoute: ProductIndexLazyRoute,
  ProfileIndexLazyRoute: ProfileIndexLazyRoute,
  RoomIndexLazyRoute: RoomIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
